New post postgresql backup
sharektech/sharektech.com pull request #11
Opened 2022-06-18 20:23 UTC by ahmedalmulla

Salam team,

Kindly review the new post and share your comments :)

2022-06-19 20:30 UTC, malnajdi requested changes
Salam @ahmedalmulla just ensure you go over the post again and read it a second time.

2022-06-19 20:30 UTC, malnajdi commented on content/posts/2022-06-15-postgresql-database-backup.md
> +title: 'النسخ الإحتياطي  لقاعدة بيانات Postgresql'
```suggestion
title: 'النسخ الإحتياطي لقاعدة البيانات Postgresql'
```

2022-06-19 20:30 UTC, malnajdi commented on content/posts/2022-06-15-postgresql-database-backup.md
> +مما لاشك فيه أن من أهم أهداف قاعدة البيانات هو حفظ البيانات وإسترجعها بشكل يسهل التعامل معها ولكن ماذا لو حدث أي عطل لنظام قواعد البيانات. ماهي  القيمة من تطبيق يعمل  مع فقدان بيانات المنظمة؟. كون نظ
I think the above needs some rephrasing

2022-06-19 20:30 UTC, malnajdi commented on content/posts/2022-06-15-postgresql-database-backup.md
> +في هذا المقال سوف نتعرف على بعض الأدوات  التي تقوم بعمل نسخ إحتياطي لقاعدة بيانات `Postgresql` وهي أدوات تكون متوفرة مع عملية تثبيت قاعدة البيانات `Postgresql` بشكل إفتراضي.
```suggestion
في هذا المقال سوف نتعرف على بعض الأدوات التي تقوم بعمل نسخ إحتياطي لقاعدة البيانات `Postgresql` وهي أدوات تكون متوفرة مع عملية تثبيت قاعدة البيانات `Postgresql` بشكل إفتراضي.
```

2022-06-19 20:30 UTC, malnajdi commented on content/posts/2022-06-15-postgresql-database-backup.md
> +في المنظمات الكبيرة والمتوسطة عادة مايكون هناك نظام متكامل لأخذ نسخ إحتياطي من جميع الأنظمة ومن ضمنها قواعد البيانات المختلفة. ولكن معرفة هذي الأدوات تساعد كثيرا في فهم كيفية عمل النسخ الإحتياطي لقوا
```suggestion
في المنظمات الكبيرة والمتوسطة عادة مايكون هناك نظام متكامل لأخذ نسخ إحتياطي من جميع الأنظمة ومن ضمنها قواعد البيانات المختلفة. ولكن معرفة هذي الأدوات تساعد كثيرا في فهم كيفية عمل النسخ الإحتياطي لقواعد البيانات وكيفية إستراجعها وتسهل معرفة المشاكل التي قد تواجها حين التعامل مع أنظمة النسخ الإحتياطي والتي قد تعتمد و تعمل في الخلفية `background` على أدوات مقدمة من أنظمة قواعد البيانات.
```

2022-06-19 20:30 UTC, malnajdi commented on content/posts/2022-06-15-postgresql-database-backup.md
> +هناك نوعين رئيسين من أنواع النسخ الإحتياطي . النوع الأول هو نسخ ملفات قواعد البيانات
```suggestion
هناك نوعين رئيسين من أنواع النسخ الإحتياطي. النوع الأول هو نسخ ملفات قواعد البيانات 
```

2022-06-19 20:30 UTC, malnajdi commented on content/posts/2022-06-15-postgresql-database-backup.md
> +لكل نوع من هذي الانواع مميزات وماهو ماسوف نقوم بشرحه بشكل مختصر في القسم التالي ولكن من الأفضل دائما جدولة نسخ إحتياطي من النوعين.
```suggestion
لكل نوع من هذه الانواع مميزات وهذا ماسوف نقوم بشرحه بشكل مختصر في القسم التالي ولكن من الأفضل دائما جدولة نسخ إحتياطي من النوعين.
```

2022-06-19 20:30 UTC, malnajdi commented on content/posts/2022-06-15-postgresql-database-backup.md
> +هذه الأداة تقبل خيارات متعددة ، سوف نتطرق لأهم خيارين فيها ويمكنك مراجعة جميع الخيارات   المتاحة من التوثيق الرسمي ل
```suggestion
هذه الأداة تقبل خيارات متعددة ، سوف نتطرق لأهم خيارين فيها ويمكنك مراجعة جميع الخيارات المتاحة من المرجع الرسمي ل 
```

2022-06-20 22:31 UTC, ahmedalmulla commented on content/posts/2022-06-15-postgresql-database-backup.md
> +title: 'النسخ الإحتياطي  لقاعدة بيانات Postgresql'
ماعتقد مفروض نكتب البيانات لانها مرتبطه بالكلمه الي بعدها مثل المواضيه الي قبل. قاعدة بيانات بوستقرس. ولا شرايك؟

2022-06-22 05:21 UTC, malnajdi approved these changes
Great job

2022-06-22 20:49 UTC, merged