review new post
sharektech/sharektech.com pull request #14
Opened 2022-09-04 20:45 UTC by ahmedalmulla

Dear Mohammed ,

we need your usual assistance to review my post and share your kind feedback.

2022-09-05 02:05 UTC, malnajdi requested changes
@ahmedalmulla kindly remove the committed file `content/.DS_Store` and add it to gitignore 
Also make sure to ensure this is for postgresql version 13, you can add it also to the tags `postgresql@13`

2022-09-05 02:05 UTC, malnajdi commented on content/posts/2022-08-13-postgresql-database-restore.md
> +### إستعادة النسخ المادي(Physical Restore)
هل نأخذ بالإعتبار تسمية النسخ المادي إلى `النسخ الكامل للملفات` ولا غير صحيح ؟
فقط أحاول ابتعد عن الترجمة الحرفية.

2022-09-05 02:05 UTC, malnajdi commented on content/posts/2022-08-13-postgresql-database-restore.md
> +`logical backup`، ولكن يمكن إنشاء قاعدة بيانات جديدة وعمل إستعادة من النسخة المنطقية إو اللجوء للنسخة الإحتياطية المادية `phyiscal backup`.
```suggestion
`logical backup`، ولكن يمكن إنشاء قاعدة بيانات جديدة وعمل إستعادة من النسخة المنطقية او اللجوء للنسخة الإحتياطية المادية `phyiscal backup`.
```

2022-09-05 02:05 UTC, malnajdi commented on content/posts/2022-08-13-postgresql-database-restore.md
> +يستخدم هذا النوع عندما يكون  حجم قواعد البيانات كبير وذلك لأنه يعد أسرع بكثير في عملية النسخ والإستعادة.
```suggestion
يستخدم هذا النوع عندما يكون حجم قواعد البيانات كبير وذلك لأنه يعد أسرع بكثير في عملية النسخ والإستعادة.
```

2022-09-05 02:05 UTC, malnajdi commented on content/posts/2022-08-13-postgresql-database-restore.md
> +1- يجب إيقاف خدمة قاعدة البيانات عن طريق مستخدم لدية الصلاحيات  `Postgresql service`:
```suggestion
1- يجب إيقاف خدمة قاعدة البيانات عن طريق مستخدم لدية الصلاحيات `Postgresql service`:
```

2022-09-05 02:05 UTC, malnajdi commented on content/posts/2022-08-13-postgresql-database-restore.md
> +- خيار `d` يستخدم للإتصال بأي قاعدة بيانات موجودة في نظام قواعد البيانات.
```suggestion
- خيار `d` يستخدم للإتصال بأي قاعدة بيانات موجودة في **نظام** قواعد البيانات.
```
نظام ام سيرفر ؟

2022-09-05 02:05 UTC, malnajdi commented on content/posts/2022-08-13-postgresql-database-restore.md
> +تم شرح كيفية  إستعادة النسخ الإحتياطية لقاعدة بيانات   `Postgresql`
```suggestion
تم شرح كيفية إستعادة النسخ الإحتياطية لقاعدة بيانات `Postgresql` 
```

2022-09-05 02:05 UTC, malnajdi commented on content/posts/2022-08-13-postgresql-database-restore.md
> +بإستخدام نوعين مختلفين من أنواع النُسخ الإحتياطية(`Physical` & `Logical`).
```suggestion
بإستخدام نوعين مختلفين من أنواع النُسخ الإحتياطية (`Physical` & `Logical`).
```

2022-09-06 16:16 UTC, sharektech commented on content/posts/2022-08-13-postgresql-database-restore.md
> +### إستعادة النسخ المادي(Physical Restore)
كلامك جميل لكن هو متعارف عليه كمصطلح physical backup. برأيي ان يكون نفس المصطلح.

2022-09-06 16:19 UTC, sharektech commented on content/posts/2022-08-13-postgresql-database-restore.md
> +`logical backup`، ولكن يمكن إنشاء قاعدة بيانات جديدة وعمل إستعادة من النسخة المنطقية إو اللجوء للنسخة الإحتياطية المادية `phyiscal backup`.
done

2022-09-06 16:22 UTC, sharektech commented on content/posts/2022-08-13-postgresql-database-restore.md
> +يستخدم هذا النوع عندما يكون  حجم قواعد البيانات كبير وذلك لأنه يعد أسرع بكثير في عملية النسخ والإستعادة.
done

2022-09-06 16:22 UTC, sharektech commented on content/posts/2022-08-13-postgresql-database-restore.md
> +1- يجب إيقاف خدمة قاعدة البيانات عن طريق مستخدم لدية الصلاحيات  `Postgresql service`:
done

2022-09-06 16:23 UTC, sharektech commented on content/posts/2022-08-13-postgresql-database-restore.md
> +- خيار `d` يستخدم للإتصال بأي قاعدة بيانات موجودة في نظام قواعد البيانات.
RDBMS نظام مثبت داخل السيرفر

2022-09-06 16:27 UTC, sharektech commented on content/posts/2022-08-13-postgresql-database-restore.md
> +بإستخدام نوعين مختلفين من أنواع النُسخ الإحتياطية(`Physical` & `Logical`).
done

2022-09-06 18:02 UTC, malnajdi approved these changes

2022-09-06 18:10 UTC, merged